#!/bin/bash
mv manifest-ff.json manifest.json
zip -r package-ff.zip _locales icons options src manifest.json
mv manifest.json manifest-ff.json
mv manifest-cws.json manifest.json
zip -r package-cws.zip _locales icons options src manifest.json
mv manifest.json manifest-cws.json